INSERT INTO roles (id, name, description) VALUES (1, 'ROLE_ADMIN', 'Administrator');
INSERT INTO roles (id, name, description) VALUES (2, 'ROLE_USER', 'User');

-- Hashed passwords generated by https://www.browserling.com/tools/bcrypt using 10 rounds
-- Password for both users is: password
INSERT INTO users (id, email, username, name, password, enabled)
    VALUES (1, 'user01@example.com', 'user01', 'John', '$2a$10$fNsiLz3EMcHs1UNPJIZDQegwNu6Gkita23NkweqdlK7GslBBCwzl2', 1);
INSERT INTO users (id, email, username, name, password, enabled)
    VALUES (2, 'admin01@example.com', 'admin01', 'Karol', '$2a$10$fNsiLz3EMcHs1UNPJIZDQegwNu6Gkita23NkweqdlK7GslBBCwzl2', 1);

INSERT INTO users_roles (user_id, role_id) VALUES (1, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 1);